server:
  port: 8080
spring:
  redis:
    redisson:
      # 如果该值为false，系统将不会创建RedissionClient的bean。
      enabled: true
      # mode的可用值为，single/cluster/sentinel/master-slave
      mode: single
      address: redis://127.0.0.1:6379
      # redis 密码，空可以不填。
      password:
      database: 9

